import random
import pandas as pd
import numpy as np
def task_func(n,
          domain="samplewebsite.com",
          categories=['Sports', 'Technology', 'Health', 'Science', 'Business'],
          random_seed=None):
    """
    Generate 'n' random articles with titles, URLs, IDs, categories, and views, and return them as a DataFrame.
    Views are generated by sampling from a poisson distribution with lambda=1000.
    """
    if random_seed:
        random.seed(random_seed)

    # Generate random article titles
    titles = [f"Article {i}" for i in range(n)]

    # Generate random article URLs
    urls = [f"{domain}/Article_{i}" for i in range(n)]

    # Generate random article IDs
    ids = [i for i in range(n)]

    # Generate random article categories
    categories = random.choices(categories, k=n)

    # Generate random article views
    views = [np.random.poisson(1000, size=1)[0] for i in range(n)]

    # Create a DataFrame with the generated data
    df = pd.DataFrame({
        "title": titles,
        "title_url": urls,
        "id": ids,
        "category": categories,
        "views": views
    })

    return df