def get_versions():
	"""
	Obtains the version information. If the version information cannot be obtained, the default value is returned.
	"""
	return {
		"version": "1.0.0",
		"version_major": "1",
		"version_minor": "0",
		"version_patch": "0",
		"version_build": "0",
		"version_build_number": "0",
		"version_build_string": "0",
		"version_build_date": "0",
		"version_build_time": "0",
		"version_build_year": "0",
		"version_build_month": "0",
		"version_build_day": "0",
		"version_build_hour": "0",
		"version_build_minute": "0",
		"version_build_second": "0",
		"version_build_millisecond": "0",
		"version_build_microsecond": "0",
		"version_build_nanosecond": "0",
		"version_build_timestamp": "0",
		"version_build_utc_timestamp": "0",
		"version_build_utc_date": "0",
		"version_build_utc_time": "0",
		"version_build_utc_year": "0",
		"version_build_utc_month": "0",
		"version_build_utc_day": "0",
		"version_build_utc_hour": "0",
		"version_build_utc_minute": "0",
		"version_build_utc_second": "0",
		"version_build_utc_millisecond": "0",
		"version_build_utc_microsecond": "0",
		"version_build_utc_nanosecond": "0",
		"version_build_utc_timestamp": "0",
		"version_build_utc_date_time": "0",
		"version_build_utc_date_time_stamp": "0",
		"version_build_utc_