import java.util.*;
import java.lang.reflect.*;
import org.javatuples.*;
import java.security.*;
import java.math.*;
import java.io.*;
import java.util.stream.*;
class Problem {
    // xs represent coefficients of a polynomial.
    // xs[0] + xs[1] * x + xs[2] * x^2 + ....
    // Return derivative of this polynomial in the same form.
    // >>> derivative((new ArrayList<Long>(Arrays.asList((long)3l, (long)1l, (long)2l, (long)4l, (long)5l))))
    // (new ArrayList<Long>(Arrays.asList((long)1l, (long)4l, (long)12l, (long)20l)))
    // >>> derivative((new ArrayList<Long>(Arrays.asList((long)1l, (long)2l, (long)3l))))
    // (new ArrayList<Long>(Arrays.asList((long)2l, (long)6l)))
    public static ArrayList<Long> derivative(ArrayList<Long> xs) {

        // Write your code here
        // 1. 原函数在0处的值为xs[0], 斜率为xs[1]
        // 2. 原函数在x处的值为xs[0]+xs[1]*x+xs[2]*x^2+....
        // 3. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 4. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 5. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 6. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 7. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 8. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 9. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 10. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 11. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 12. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 13. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 14. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 15. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 16. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 17. 原函数在x处的斜率为xs[1]+2*xs[2]*x+3*xs[3]*x^2+...
        // 18. 原函数在x处的����
    }
    public static void main(String[] args) {
    assert(derivative((new ArrayList<Long>(Arrays.asList((long)3l, (long)1l, (long)2l, (long)4l, (long)5l)))).equals((new ArrayList<Long>(Arrays.asList((long)1l, (long)4l, (long)12l, (long)20l)))));
    assert(derivative((new ArrayList<Long>(Arrays.asList((long)1l, (long)2l, (long)3l)))).equals((new ArrayList<Long>(Arrays.asList((long)2l, (long)6l)))));
    assert(derivative((new ArrayList<Long>(Arrays.asList((long)3l, (long)2l, (long)1l)))).equals((new ArrayList<Long>(Arrays.asList((long)2l, (long)2l)))));
    assert(derivative((new ArrayList<Long>(Arrays.asList((long)3l, (long)2l, (long)1l, (long)0l, (long)4l)))).equals((new ArrayList<Long>(Arrays.asList((long)2l, (long)2l, (long)0l, (long)16l)))));
    assert(derivative((new ArrayList<Long>(Arrays.asList((long)1l)))).equals((new ArrayList<Long>(Arrays.asList()))));
    }

}
