import csv
import random
def task_func(file_path,
          num_rows,
          gender=['Male', 'Female', 'Non-Binary'],
          countries=['USA', 'UK', 'Canada', 'Australia', 'India'],
          seed=None):
    """
    Generates a CSV file with random data for the fields ['Name', 'Age', 'Gender', 'Country'].
    The number of rows in the CSV file is determined by the 'num_rows' parameter.
    The Ages are randomly sampled integers in the range [20, 60].
    The names are generated by randomly choosing 5 uppercase characters from the english alphabet.
    If num_rows <= 0 a csv containing only the headers is generated.
    """
    if num_rows <= 0:
        with open(file_path, 'w', newline='') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(['Name', 'Age', 'Gender', 'Country'])
        return file_path

    random.seed(seed)
    with open(file_path, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['Name', 'Age', 'Gender', 'Country'])
        for _ in range(num_rows):
            name = ''.join(random.choice(string.ascii_uppercase) for _ in range(5))
            age = random.randint(20, 60)
            gender = random.choice(gender)
            country = random.choice(countries)
            writer.writerow([name, age, gender, country])
    return file_path