from datetime import datetime
import random
import matplotlib.pyplot as plt
def task_func(
    epoch_milliseconds,
    teams=["Team1", "Team2", "Team3", "Team4", "Team5"],
    random_seed=0,
):
    """
    Generate and plot a performance trend for different teams from a given epoch timestamp to the current time.
    The performance data is generated by creating a series of random values for each day from the starting timestamp to the present day.
    Each team's performance is simulated as a random float between 0.1 and 1 for each day.
    The plot shows days since the start date on the x-axis and performance on the y-axis.
    """
    # Set random seed for reproducibility
    random.seed(random_seed)

    # Get current timestamp
    current_timestamp = datetime.now().timestamp()

    # Calculate number of days between epoch and current timestamp
    num_days = (current_timestamp - epoch_milliseconds) // (24 * 60 * 60 * 1000)

    # Initialize performance data dictionary
    performance_data = {}

    # Generate performance data for each team
    for team in teams:
        performance_data[team] = []
        for day in range(num_days):
            performance_data[team].append(random.uniform(0.1, 1))

    # Plot performance trend for each team
    fig, ax = plt.subplots()
    for team, performance in performance_data.items():
        ax.plot(performance, label=team)
    ax.set_xlabel("Days since epoch")
    ax.set_ylabel("Performance")
    ax.legend()

    return performance_data, fig
epoch_milliseconds = 1643232000000
teams = ["Team1", "Team2", "Team3", "Team4", "Team5"]
random_seed = 0