import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
def task_func(mu=0, sigma=1, sample_size=1000, seed=0):
    np.random.seed(seed)
    sample = np.random.normal(mu, sigma, sample_size)
    ax = plt.hist(sample, bins=50, density=True, alpha=0.5, label='Sample')
    ax.set_title(f'Normal Distribution with $\\mu = {mu}, \\sigma = {sigma}$')
    ax.set_xlabel('Value')
    ax.set_ylabel('Density')
    ax.legend()
    ax.set_xlim([-5, 5])
    ax.set_ylim([0, 0.3])
    ax.set_xticks([-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5])
    ax.set_yticks([0, 0.1, 0.2, 0.3])
    ax.set_xticklabels([-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5])
    ax.set_yticklabels([0, 0.1, 0.2, 0.3])
    ax.grid(True)
    ax.set_facecolor('white')
    ax.set_aspect(1)
    ax.set_frameon(False)
    ax.set_box_aspect(1)
    ax.set_box_color('white')
    ax.set_box_on(False)
    ax.set_spines(False)
    ax.set_spine_color('white')
    ax.set_spine_on(False)
    ax.set_tick_params(axis='x', which='both', bottom=False, top=False, labelbottom=False)
    ax.set_tick_params(axis='y', which='both', left=False, right=False, labelleft=False)
    ax.set_tick_params(axis='x', which='major', labelsize=10)
    ax.set_tick_params(axis='y', which='major', labelsize=10)
    ax.set_tick_params(axis='x', which='minor', labelsize=8)
    ax.set_tick_params(axis='y', which='minor', labelsize=8)
    ax.set_tick_params(axis='x', which='both', direction='in')
    ax.set_tick_params(axis='y', which='both', direction='in')
    ax.set_tick_params(axis='x', which='major', length=5)
    ax.set_tick_params(axis='y', which='major', length=5)
    ax.set_tick_params(axis='x', which='minor', length=3)
    ax.set_tick_params(axis='y', which='minor', length=3)
    ax.set_tick_params(axis='x', which='both', width=1)
    ax.set_tick_params(axis='y', which='both', width=1)
    ax.set_tick_params(axis='x', which='major', width=1)
    ax.set_tick_params(axis='y', which='major', width=1)
    ax.set_tick_params(axis='x', which='minor', width=1)
    ax.set_tick_params(axis='y', which='minor', width=1)
    ax.set_tick_params(axis='x', which='both', color='black')
    ax.set_tick_params(axis='y', which='both', color='black')
    ax.set_tick_params(axis='x', which='major', color='black')
    ax.set_tick_params(axis='y', which='major', color='black')
    ax.set_tick_params(axis='x', which='minor', color='black')
    ax.set_tick_params(axis='y', which='minor', color='black')
    ax.set_tick_params(axis='x', which='both', labelcolor='black')
    ax.set_tick_params(axis='y', which='both', labelcolor='black')
    ax.set_tick_params(axis='x', which='major', labelcolor='black')
    ax.set_tick_params(axis='y', which='major', labelcolor='black')
    ax.set_tick_params(axis='x', which='minor', labelcolor='black')
    ax.set_tick_params(axis='y', which='minor', labelcolor='black')
    ax.set_tick_params(axis='x', which='both', labelsize=10)
    ax.set_tick_params(axis='y', which='both', labelsize=10)
    ax.set_tick_params(axis='x', which='major', labelsize=10)
    ax.set_tick_params(axis='y', which='major', labelsize=10)
    ax.set_tick_params(axis='x', which='minor', labelsize=8)