from datetime import datetime
import random
import matplotlib.pyplot as plt
def task_func(
    epoch_milliseconds,
    teams=["Team1", "Team2", "Team3", "Team4", "Team5"],
    random_seed=0,
):
    """
    Generate and plot a performance trend for different teams from a given epoch timestamp to the current time.

    The performance data is generated by creating a series of random values for each day from the starting timestamp
    to the present day. Each team's performance is simulated as a random float between 0.1 and 1 for each day.
    The plot shows days since the start date on the x-axis and performance on the y-axis.

    Parameters:
    epoch_milliseconds (int): The epoch milliseconds from where to start the generation. Must not be in the future.
    teams (list of str, optional): Team names. If not provided, defaults to ['Team1', 'Team2', 'Team3', 'Team4', 'Team5'].
    random_seed (int, optional): Seed for random number generation to ensure reproducibility. Defaults to 0.

    Returns:
    dict: A dictionary containing performance data for each team, with days as indices and performance as float values.
    matplotlib.figure.Figure: A figure object showing the performance trend of each team over the days.

    Requirements:
    - datetime.datetime
    - random
    - matplotlib

    Example:
    >>> results, ax = task_func(1236472051807)
    >>> results.keys()
    dict_keys(['Team1', 'Team2', 'Team3', 'Team4', 'Team5'])
    >>> type(ax)
    <class 'matplotlib.figure.Figure'>
    """
    # Generate performance data for each team
    performance = {}
    for team in teams:
        performance[team] = []

    # Generate random performance for each team for each day
    start_date = datetime.fromtimestamp(epoch_milliseconds / 1000)
    current_date = datetime.now()
    days = (current_date - start_date).days
    random.seed(random_seed)
    for day in range(days):
        for team in teams:
            performance[team].append(random.random() * 0.9 + 0.1)

    # Plot performance trend
    fig, ax = plt.subplots()
    ax.set_title("Performance trend")
    ax.set_xlabel("Days since " + str(start_date.date()))
    ax.set_ylabel("Performance")
    ax.set_ylim(0, 1)
    ax.set_xlim(0, days)
    ax.grid(True)
    for team in teams:
        ax.plot(
            range(days),
            performance[team],
            label=team,
            marker="o",
            markersize=10,
            markerfacecolor="none",
            markeredgecolor="black",
        )
    ax.legend()

    return performance, fig