
import seaborn as sns
from scipy.stats import chi2_contingency
def task_func(df1, df2, column1="feature1", column2="feature2"):
    # Merge the two dataframes based on the 'id' column
    merged_df = pd.concat([df1, df2], axis=1)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True)
    merged_df.drop_duplicates(subset=["id"], inplace=True