
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import matplotlib.pyplot as plt
# Constants
STOP_WORDS = ["a", "an", "the", "in", "on", "at", "and", "or"]
def task_func(file_path, save_path=None):
    # Load the data
    data = pd.read_csv(file_path)
    # Preprocess the text data
    data = data.apply(lambda x: x.lower())
    data = data.apply(lambda x: x.replace("_", " "))
    data = data.apply(lambda x: x.replace("-", " "))
    data = data.apply(lambda x: x.replace("?", " "))
    data = data.apply(lambda x: x.replace("!", " "))
    data = data.apply(lambda x: x.replace(":", " "))
    data = data.apply(lambda x: x.replace(",", " "))
    data = data.apply(lambda x: x.replace(".", " "))
    data = data.apply(lambda x: x.replace(";", " "))
    data = data.apply(lambda x: x.replace("(", " "))
    data = data.apply(lambda x: x.replace(")", " "))
    data = data.apply(lambda x: x.replace("[", " "))
    data = data.apply(lambda x: x.replace("]", " "))
    data = data.apply(lambda x: x.replace("{", " "))
    data = data.apply(lambda x: x.replace("}", " "))
    data = data.apply(lambda x: x.replace("'", " "))
    data = data.apply(lambda x: x.replace("`", " "))
    data = data.apply(lambda x: x.replace("\"", " "))
    data = data.apply(lambda x: x.replace("\\", " "))
    data = data.apply(lambda x: x.replace("&", " "))
    data = data.apply(lambda x: x.replace("*", " "))
    data = data.apply(lambda x: x.replace("+", " "))
    data = data.apply(lambda x: x.replace("-", " "))
    data = data.apply(lambda x: x.replace("=", " "))
    data = data.apply(lambda x: x.replace(";", " "))
    data = data.apply(lambda x: x.replace(":", " "))
    data = data.apply(lambda x: x.replace(")", " "))
    data = data.apply(lambda x: x.replace("(", " "))
    data = data.apply(lambda x: x.replace("[", " "))
    data = data.apply(lambda x: x.replace("]", " "))
    data = data.apply(lambda x: x.replace("{", " "))
    data = data.apply(lambda x: x.replace("}", " "))
    data = data.apply(lambda x: x.replace("'", " "))
    data = data.apply(lambda x: x.replace("`", " "))
    data = data.apply(lambda x: x.replace("\"", " "))
    data = data.apply(lambda x: x.replace("\\", " "))
    data = data.apply(lambda x: x.replace("&", " "))
    data = data.apply(lambda x: x.replace("*", " "))
    data = data.apply(lambda x: x.replace("+", " "))
    data = data.apply(lambda x: x.replace("-", " "))
    data = data.apply(lambda x: x.replace("=", " "))
    data = data.apply(lambda x: x.replace(";", " "))
    data = data.apply(lambda x: x.replace(":", " "))
    data = data.apply(lambda x: x.replace(")", " "))
    data = data.apply(lambda x: x.replace("(", " "))
    data = data.apply(lambda x: x.replace("[", " "))
    data = data.apply(lambda x: x.replace("]", " "))
    data = data.apply(lambda x: x.replace("{", " "))
    data = data.apply(lambda x: x.replace("}", " "))
    data = data.apply(lambda x: x.replace("'", " "))
    data = data.apply(lambda x: x.replace("`", " "))
    data = data.apply(lambda x: x.replace("\"", " "))
    data = data.apply(lambda x: x.replace("\\", " "))
    data = data.apply(lambda x: x.replace("&", " "))
    data = data.apply(lambda x: x.replace("*", " "))
    data = data.apply(lambda x: x.replace("+", " "))
    data = data.apply(lambda x: x.replace("-", " "))
    data = data.apply(lambda x: x.replace("=", " "))
    data = data.apply(lambda x: x.replace(";", " "))
    data = data.apply