
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

def task_func(file_path: str, plot_path: str) -> (float, float, str):
    if not os.path.exists(file_path):
        raise FileNotFoundError("File not found")
    data = pd.read_csv(file_path)
    data = data.drop(data.columns[0], axis=1)
    data = data.drop(data.index[0], axis=0)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[0], axis=0)
    data = data.drop(data.columns[0], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[0], axis=0)
    data = data.drop(data.columns[0], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[0], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data = data.drop(data.index[-1], axis=0)
    data = data.drop(data.columns[-1], axis=1)
    data