
import pandas as pd
import numpy as np
import itertools

def task_func(data_list=[('a', 1, 2.1), ('b', 2, 3.2), ('c', 3, 4.3), ('d', 4, 5.4), ('e', 5, 6.5)]):
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (int, float)) and x != '']
    data_list = [x for x in data_list if x != '']
    data_list = [x for x in data_list if isinstance(x, (