
import matplotlib.pyplot as plt
import pandas as pd
import random
from datetime import datetime

def task_func(seed=42):
    # Set the random seed for reproducibility
    random.seed(seed)

    # Generate the time series data
    data = pd.Series(random.normal(100, 10, 30), index=pd.date_range(start=datetime(2023, 1, 1), end=datetime(2023, 2, 1), freq='D'))

    # Plot the data
    fig, ax = plt.subplots(figsize=(12, 6))
    ax.plot(data)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strftime('%d %b %Y'))
    ax.set_xticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time Series Data')
    ax.set_facecolor('white')
    ax.set_xticklabels(data.index.strfticklabels(rotation=45)
    ax.set_xlabel('Date')
    ax.set_ylabel('Value')
    ax.set_title('Random Time