
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

def task_func(num_samples=1000, k=5, d=2, random_seed=None):
    # Generate a dataset of random numbers sampled from a gaussian normal distribution
    np.random.seed(random_seed)
    X = np.random.normal(0, 1, (num_samples, k))

    # Apply a linear transformation to the data
    A = np.random.normal(0, 1, (k, d))
    B = np.random.normal(0, 1, (d, d))
    C = np.random.normal(0, 1, (d, d))
    D = np.random.normal(0, 1, (d, d))
    E = np.random.normal(0, 1, (d, d))
    F = np.random.normal(0, 1, (d, d))
    G = np.random.normal(0, 1, (d, d))
    H = np.random.normal(0, 1, (d, d))
    I = np.random.normal(0, 1, (d, d))
    J = np.random.normal(0, 1, (d, d))
    K = np.random.normal(0, 1, (d, d))
    L = np.random.normal(0, 1, (d, d))
    M = np.random.normal(0, 1, (d, d))
    N = np.random.normal(0, 1, (d, d))
    O = np.random.normal(0, 1, (d, d))
    P = np.random.normal(0, 1, (d, d))
    Q = np.random.normal(0, 1, (d, d))
    R = np.random.normal(0, 1, (d, d))
    S = np.random.normal(0, 1, (d, d))
    T = np.random.normal(0, 1, (d, d))
    U = np.random.normal(0, 1, (d, d))
    V = np.random.normal(0, 1, (d, d))
    W = np.random.normal(0, 1, (d, d))
    X = np.random.normal(0, 1, (d, d))
    Y = np.random.normal(0, 1, (d, d))
    Z = np.random.normal(0, 1, (d, d))
    a = np.random.normal(0, 1, (d, d))
    b = np.random.normal(0, 1, (d, d))
    c = np.random.normal(0, 1, (d, d))
    d = np.random.normal(0, 1, (d, d))
    e = np.random.normal(0, 1, (d, d))
    f = np.random.normal(0, 1, (d, d))
    g = np.random.normal(0, 1, (d, d))
    h = np.random.normal(0, 1, (d, d))
    i = np.random.normal(0, 1, (d, d))
    j = np.random.normal(0, 1, (d, d))
    k = np.random.normal(0, 1, (d, d))
    l = np.random.normal(0, 1, (d, d))
    m = np.random.normal(0, 1, (d, d))
    n = np.random.normal(0, 1, (d, d))
    o = np.random.normal(0, 1, (d, d))
    p = np.random.normal(0, 1, (d, d))
    q = np.random.normal(0, 1, (d, d))
    r = np.random.normal(0, 1, (d, d))
    s = np.random.normal(0, 1, (d, d))
    t = np.random.normal(0, 1, (d, d))
    u = np.random.normal(0, 1, (d, d))
    v = np.random.normal(0, 1, (d, d))
    w = np.random.normal(0, 1, (d, d))
    x = np.random.normal(0, 1, (d, d))
    y = np.random.normal(0, 1, (d, d))
    z = np.random.normal(0, 1, (d, d))
    a = np.random.normal(0, 1, (d, d))
    b = np.random.normal(0, 1, (d, d))
    c = np.random.normal(0, 1, (d, d))
    d = np.random.normal(0, 1, (d, d))
    e = np.random.normal(0, 1, (d, d))
    f = np.random.normal(0, 1