
import collections
from operator import itemgetter
import matplotlib.pyplot as plt

def task_func(data):
    counts = collections.Counter(data)
    counts = sorted(counts.items(), key=itemgetter(1), reverse=True)
    max_count = counts[0][1]
    max_letter = counts[0][0]
    fig, ax = plt.subplots()
    ax.bar(counts[:, 0], counts[:, 1])
    ax.set_xlabel('Letter')
    ax.set_ylabel('Count')
    ax.set_title('Letter Counts with Max Value Letter Highlighted')
    ax.legend(('Letter Counts', 'Max Value Letter'))
    ax.set_xticks(ax.get_xticks()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticks(ax.get_yticks()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])
    ax.set_xticklabels(ax.get_xticklabels()[0:10])
    ax.set_yticklabels(ax.get_yticklabels()[0:10])