
import requests
from PIL import Image
import io
from PIL.PngImagePlugin import ImagePngHeader
from PIL.JpegImagePlugin import JpegImagePlugin
from PIL.GifImagePlugin import GifImagePlugin
from PIL.BmpImagePlugin import BmpImagePlugin
from PIL.TiffImagePlugin import TiffImagePlugin
from PIL.SunImagePlugin import SunImagePlugin
from PIL.BdfImagePlugin import BdfImagePlugin
from PIL.PcxImagePlugin import PcxImagePlugin
from PIL.PpmImagePlugin import PpmImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import PngImagePlugin
from PIL.PngImagePlugin import P