def int_to_mini_roman(number: int) -> str:
    """
    Given a positive integer, obtain its roman numeral equivalent as a string,
    and return it in lowercase.
    Restrictions: 1 <= num <= 1000

    Examples:
    >>> int_to_mini_roman(19)
    'xix'
    >>> int_to_mini_roman(152)
    'clii'
    >>> int_to_mini_roman(426)
    'cdxxvi'
    """

    if not 1 <= number <= 1000:
        raise ValueError(f"Number out of range: {number}")
    int_to_roman = {
        1: "i",
        2: "ii",
        3: "iii",
        4: "iv",
        5: "v",
        6: "vi",
        7: "vii",
        8: "viii",
        9: "ix",
        10: "x",
        11: "xi",
        12: "xii",
        13: "xiii",
        14: "xiv",
        15: "xv",
        16: "xvi",
        17: "xvii",
        18: "xviii",
        19: "xix",
        20: "xx",
        21: "xxi",
        22: "xxii",
        23: "xxiii",
        24: "xxiv",
        25: "xxv",
        26: "xxvi",
        27: "xxvii",
        28: "xxviii",
        29: "xxix",
        30: "xxx",
        31: "xxxi",
        32: "xxxii",
        33: "xxxiii",
        34: "xxxiv",
        35: "xxxv",
        36: "xxxvi",
        37: "xxxvii",
        38: "xxxviii",
        39: "xxxix",
        40: "xl",
        41: "xli",
        42: "xlii",
        43: "xliii",
        44: "xliv",
        45: "xlv",
        46: "xlvi",
        47: "xlvii",
        48: "xlviii",
        49: "xlix",
        50: "l",
        51: "li",
        52: "lii",
        53: "liii",
        54: "liv",
        55: "lv",
        56: "lvi",
        57: "lvii",
        58: "lviii",
        59: "lix",
        60: "lx",
        61: "lxi",
        62: "lxii",
        63: "lxiii",
        64: "lxiv",
        65: "lxv",
        66: "lxvi",
        67: "lxvii",
        68: "lxviii",
        69: "lxix",
        70: "lxx",
        71: "lxxi",
        72: "lxxii",
        73: "lxxiii",
        74: "lxxiv",
        75: "lxxv",
        76: "lxxvi",
        77: "lxxvii",
        78: "lxxviii",
        79: "lxxix",
        80: "lxxx",
        81: "lxxxi",
        82: "lxxxii",
        83: "lxxxiii",
        84: "lxxxiv",
        85: "lxxxv",
        86: "lxxxvi",
        87: "lxxxvii",
        88: "lxxxviii",
        89: "lxxxix",
        90: "xc",
        91: "xci",
        92
