
import subprocess
import os
import time
import glob

def task_func(r_script_path: str, output_path: str, duration: int) -> (bool, str):
    """
    Executes an R script and verifies if the output file is generated within a given duration.

    Parameters:
        r_script_path (str): Path to the R script to be executed.
        output_path (str): Path to the output file generated by the R script.
        duration (int): Duration in seconds within which the output file should be generated.

    Returns:
        tuple: A tuple containing a boolean value indicating whether the output file was generated within the specified duration, and a message indicating the status of the operation.
    """
    # Execute the R script
    subprocess.run(r_script_path, shell=True)

    # Wait for the output file to be generated
    start_time = time.time()
    while not os.path.exists(output_path):
        time.sleep(0.1)
        if time.time() - start_time > duration:
            return False, "File not generated within the specified duration."

    # Check if the output file is generated
    if os.path.exists(output_path):
        return True, "File generated successfully within the specified duration."
    else:
        return False, "File not generated within the specified duration."