
from random import choice
import turtle
import time

def task_func(colors):
    # Set up the Turtle graphics window
    window = turtle.Screen()
    window.setup(width=500, height=500)
    window.title("Turtle Graphics")
    window.bgcolor("white")

    # Create a Turtle object
    turtle = turtle.Turtle()
    turtle.shape("square")
    turtle.color("black")
    turtle.speed(0)

    # Draw the squares with colors from the provided list
    for i in range(5):
        turtle.penup()
        turtle.goto(0, 0)
        turtle.pendown()
        turtle.color(choice(colors))
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.penup()
        turtle.goto(0, 0)
        turtle.pendown()
        turtle.color("black")
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.penup()
        turtle.goto(0, 0)
        turtle.pendown()
        turtle.color("black")
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.penup()
        turtle.goto(0, 0)
        turtle.pendown()
        turtle.color("black")
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.penup()
        turtle.goto(0, 0)
        turtle.pendown()
        turtle.color("black")
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.penup()
        turtle.goto(0, 0)
        turtle.pendown()
        turtle.color("black")
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.penup()
        turtle.goto(0, 0)
        turtle.pendown()
        turtle.color("black")
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.penup()
        turtle.goto(0, 0)
        turtle.pendown()
        turtle.color("black")
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.penup()
        turtle.goto(0, 0)
        turtle.pendown()
        turtle.color("black")
        turtle.forward(100)