from datetime import datetime
import random
import matplotlib.pyplot as plt
def task_func(
    epoch_milliseconds,
    teams=["Team1", "Team2", "Team3", "Team4", "Team5"],
    random_seed=0,
):
    """
    Generate and plot a performance trend for different teams from a given epoch timestamp to the current time.
    The performance data is generated by creating a series of random values for each day from the starting timestamp to the present day.
    Each team's performance is simulated as a random float between 0.1 and 1 for each day.
    The plot shows days since the start date on the x-axis and performance on the y-axis.
    """
    # Set random seed for reproducibility
    random.seed(random_seed)

    # Convert epoch milliseconds to datetime object
    start_date = datetime.fromtimestamp(epoch_milliseconds / 1000)

    # Create a dictionary to store performance data for each team
    performance_data = {}

    # Generate performance data for each team
    for team in teams:
        performance_data[team] = []
        for i in range(0, (datetime.now() - start_date).days):
            performance_data[team].append(random.uniform(0.1, 1))

    # Create a figure object to plot the performance trend
    fig, ax = plt.subplots()

    # Plot performance data for each team
    for team in teams:
        ax.plot(performance_data[team], label=team)

    # Set x-axis label and title
    ax.set_xlabel("Days since start date")
    ax.set_ylabel("Performance")
    ax.set_title("Performance Trend for Different Teams")

    # Set legend
    ax.legend()

    # Return performance data and figure object
    return performance_data, fig