import random
import pandas as pd
import numpy as np
def task_func(n,
          domain="samplewebsite.com",
          categories=['Sports', 'Technology', 'Health', 'Science', 'Business'],
          random_seed=None):
    """
    Generate 'n' random articles with titles, URLs, IDs, categories, and views, and return them as a DataFrame.
    Views are generated by sampling from a poisson distribution with lambda=1000.
    """
    if random_seed:
        random.seed(random_seed)

    articles = []
    for i in range(n):
        title = f"Article {i}"
        title_url = f"{domain}/{title}"
        id = i
        category = random.choice(categories)
        views = np.random.poisson(1000)
        articles.append({"title": title, "title_url": title_url, "id": id, "category": category, "views": views})

    return pd.DataFrame(articles)